#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=true
bspc rule -a haruna desktop='^3' state=fullscreen follow=true
bspc rule -a Chromium desktop='^2'
bspc rule -a Thorium-browser desktop='^2'
bspc rule -a Telegram-desktop desktop="^8"
bspc rule -a discord desktop="^7" follow=false
bspc rule -a Spotify desktop="^9"

# bspc rule -a Spotify border=off
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# custom rules
bspc rule -a mpv state=floating sticky=on
bspc rule -a Textsnatcher state=floating sticky=on



# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color2"
bspc config active_border_color "$color1"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"

# bspc config ignore_ewmh_focus true
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"


#AutoStart
setxkbmap -option ctrl:nocaps
sxhkd &
xbanish &
dunst &
# swww-daemon &

picom --config $HOME/.config/picom/picom.conf &
# turn off automatic screen off after 10min
xset -dpms &
xset s off &

$HOME/.config/autostart/autostart.sh
$HOME/.config/polybar/launch.sh
